# Autenticação e cadastro do Banco ARO (Flask + Firebird).
import os
from functools import wraps
from pathlib import Path
from decimal import Decimal, InvalidOperation

import fdb
from flask import Flask, render_template, request, flash, redirect, url_for, session
from flask_bcrypt import Bcrypt

BASE = Path(__file__).resolve().parent
app = Flask(__name__, template_folder=str(BASE / 'Templates'), static_folder=str(BASE / 'Static'), static_url_path='/static')
app.config['SECRET_KEY'] = os.environ.get('ARO_SECRET_KEY', 'CHAVE-LOCAL-TROQUE-ANTES-DE-PUBLICAR')
bcrypt = Bcrypt(app)
DB_PATH = Path(os.environ.get('ARO_DB_PATH', str(BASE.parent / 'BANCO.FDB')))


def conectar():
    return fdb.connect(host=os.environ.get('ARO_DB_HOST', 'localhost'),
                       database=str(DB_PATH), user=os.environ.get('ARO_DB_USER', 'sysdba'),
                       password=os.environ.get('ARO_DB_PASSWORD', 'masterkey'), charset='UTF8')



def preparar_seguranca():
    # Migração idempotente: executar com permissão DDL.
    con = conectar()
    cur = con.cursor()
    try:
        cur.execute("SELECT TRIM(RDB$FIELD_NAME) FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'USUARIO'")
        campos = {r[0].upper() for r in cur.fetchall()}
        for nome, tipo in [('ATIVO', 'SMALLINT DEFAULT 1 NOT NULL'),
                           ('TENTATIVAS_LOGIN', 'SMALLINT DEFAULT 0 NOT NULL'),
                           ('BLOQUEADO', 'SMALLINT DEFAULT 0 NOT NULL')]:
            if nome not in campos:
                cur.execute(f'ALTER TABLE USUARIO ADD {nome} {tipo}')
                con.commit()
        cur.execute("SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'HISTORICO_SENHA'")
        if cur.fetchone()[0] == 0:
            cur.execute('''CREATE TABLE HISTORICO_SENHA (
                ID_HISTORICO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_USUARIO INTEGER NOT NULL,
                SENHA_HASH VARCHAR(255) NOT NULL,
                CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT FK_HIST_SENHA_USUARIO FOREIGN KEY (ID_USUARIO)
                    REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
            )''')
            con.commit()
        # As senhas atuais são verificadas diretamente na tabela USUARIO.
        # O histórico só armazena senhas anteriores a partir da primeira troca.
    except Exception:
        con.rollback()
        raise
    finally:
        cur.close()
        con.close()


def senha_ja_utilizada(cursor, id_usuario, nova_senha, hash_atual):
    if bcrypt.check_password_hash(hash_atual, nova_senha):
        return True
    cursor.execute('''SELECT FIRST 3 SENHA_HASH FROM HISTORICO_SENHA
                      WHERE ID_USUARIO = ? ORDER BY ID_HISTORICO DESC''', (id_usuario,))
    return any(bcrypt.check_password_hash(item[0], nova_senha) for item in cursor.fetchall())


def senha_forte(senha):
    # Validação artesanal, usando funções nativas do Python.
    return (len(senha) >= 8 and any(c.isupper() for c in senha)
            and any(c.islower() for c in senha) and any(c.isdigit() for c in senha))


def valor_monetario(texto):
    texto = (texto or '').strip().replace('R$', '').replace(' ', '')
    if ',' in texto:
        texto = texto.replace('.', '').replace(',', '.')
    try:
        valor = Decimal(texto)
        if not valor.is_finite() or valor < 0:
            raise ValueError()
        return valor
    except (InvalidOperation, ValueError):
        raise ValueError('Informe valores válidos para renda e despesas.')


def autenticado(view):
    @wraps(view)
    def protegido(*args, **kwargs):
        if 'id_usuario' not in session:
            flash('Você precisa estar logado.', 'error')
            return redirect(url_for('login'))
        con = conectar()
        cur = con.cursor()
        try:
            cur.execute('SELECT ATIVO, BLOQUEADO FROM USUARIO WHERE ID_USUARIO = ?', (session['id_usuario'],))
            situacao = cur.fetchone()
        finally:
            cur.close()
            con.close()
        if not situacao or not situacao[0] or situacao[1]:
            session.clear()
            flash('Conta inativa ou bloqueada. Entre em contato com o administrador.', 'error')
            return redirect(url_for('login'))
        return view(*args, **kwargs)
    return protegido


@app.route('/')
def landing():
    return render_template('landing.html')


@app.route('/cadastro', methods=['GET', 'POST'])
def cadastro():
    if request.method == 'GET':
        return render_template('cadastro.html')
    nome = request.form.get('nome', '').strip()
    email = request.form.get('email', '').strip().lower()
    senha = request.form.get('senha', '')
    if not nome or not email or not senha:
        flash('Preencha nome, e-mail e senha.', 'error')
        return redirect(url_for('cadastro'))
    if not senha_forte(senha):
        flash('Use pelo menos 8 caracteres, com maiúscula, minúscula e número.', 'error')
        return redirect(url_for('cadastro'))
    try:
        receita = valor_monetario(request.form.get('renda'))
        despesa = valor_monetario(request.form.get('despesas'))
    except ValueError as e:
        flash(str(e), 'error')
        return redirect(url_for('cadastro'))
    con = conectar()
    cursor = con.cursor()
    try:
        cursor.execute('SELECT 1 FROM USUARIO WHERE LOWER(EMAIL) = ?', (email,))
        if cursor.fetchone():
            flash('Este e-mail já foi cadastrado.', 'error')
            return redirect(url_for('cadastro'))
        hash_senha = bcrypt.generate_password_hash(senha).decode('utf-8')
        cursor.execute('''INSERT INTO USUARIO
            (NOME, EMAIL, SENHA, RECEITA_MENSAL, DESPESA_MENSAL, TIPO_USUARIO)
            VALUES (?, ?, ?, ?, ?, ?)''', (nome, email, hash_senha, receita, despesa, 1))
        con.commit()
        flash('Cadastro realizado! Entre na sua conta.', 'success')
        return redirect(url_for('login'))
    except Exception:
        con.rollback()
        app.logger.exception('Falha no cadastro')
        flash('Não foi possível concluir o cadastro.', 'error')
        return redirect(url_for('cadastro'))
    finally:
        cursor.close()
        con.close()


@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    email = request.form.get('email', '').strip().lower()
    senha = request.form.get('senha', '')
    con = conectar()
    cursor = con.cursor()
    try:
        cursor.execute('''SELECT ID_USUARIO, NOME, SENHA, ATIVO, TENTATIVAS_LOGIN, BLOQUEADO
                          FROM USUARIO WHERE LOWER(EMAIL) = ?''', (email,))
        usuario = cursor.fetchone()
        if not usuario:
            flash('E-mail ou senha incorretos.', 'error')
            return redirect(url_for('login'))
        id_usuario, nome, senha_hash, ativo, tentativas, bloqueado = usuario
        if not ativo:
            flash('Usuário inativo. Entre em contato com o administrador.', 'error')
            return redirect(url_for('login'))
        if bloqueado or tentativas >= 3:
            flash('Usuário bloqueado após 3 tentativas. Entre em contato com o administrador.', 'error')
            return redirect(url_for('login'))
        if not bcrypt.check_password_hash(senha_hash, senha):
            tentativas = (tentativas or 0) + 1
            cursor.execute('''UPDATE USUARIO SET TENTATIVAS_LOGIN = ?, BLOQUEADO = ?
                              WHERE ID_USUARIO = ?''', (tentativas, 1 if tentativas >= 3 else 0, id_usuario))
            con.commit()
            if tentativas >= 3:
                flash('Usuário bloqueado após 3 tentativas incorretas.', 'error')
            else:
                flash(f'E-mail ou senha incorretos. Tentativa {tentativas} de 3.', 'error')
            return redirect(url_for('login'))
        cursor.execute('UPDATE USUARIO SET TENTATIVAS_LOGIN = 0 WHERE ID_USUARIO = ?', (id_usuario,))
        con.commit()
        session.clear()
        session['id_usuario'] = id_usuario
        session['nome_usuario'] = nome
        flash('Login realizado com sucesso!', 'success')
        return redirect(url_for('inicio'))
    except Exception:
        con.rollback()
        app.logger.exception('Falha no login')
        flash('Não foi possível entrar no momento.', 'error')
        return redirect(url_for('login'))
    finally:
        cursor.close()
        con.close()


@app.route('/inicio')
@app.route('/novo')
@autenticado
def inicio():
    return render_template('inicio.html', usuario=session['nome_usuario'])


@app.route('/editar_usuario', methods=['GET', 'POST'])
@autenticado
def editar_usuario():
    # Edita o usuário autenticado sem modificar a chave primária.
    con = conectar()
    cursor = con.cursor()
    try:
        cursor.execute('''SELECT NOME, EMAIL, RECEITA_MENSAL, DESPESA_MENSAL, SENHA
                          FROM USUARIO WHERE ID_USUARIO = ?''', (session['id_usuario'],))
        usuario = cursor.fetchone()
        if not usuario:
            session.clear()
            flash('Usuário não encontrado.', 'error')
            return redirect(url_for('login'))
        if request.method == 'GET':
            return render_template('editar_usuario.html', usuario=usuario)
        nome = request.form.get('nome', '').strip()
        email = request.form.get('email', '').strip().lower()
        senha = request.form.get('senha', '')
        if not nome or not email:
            flash('Nome e e-mail são obrigatórios.', 'error')
            return redirect(url_for('editar_usuario'))
        if senha and not senha_forte(senha):
            flash('A nova senha deve ter 8 caracteres, maiúscula, minúscula e número.', 'error')
            return redirect(url_for('editar_usuario'))
        receita = valor_monetario(request.form.get('renda'))
        despesa = valor_monetario(request.form.get('despesas'))
        cursor.execute('SELECT 1 FROM USUARIO WHERE LOWER(EMAIL) = ? AND ID_USUARIO <> ?',
                       (email, session['id_usuario']))
        if cursor.fetchone():
            flash('Este e-mail já está em uso.', 'error')
            return redirect(url_for('editar_usuario'))
        if senha:
            if senha_ja_utilizada(cursor, session['id_usuario'], senha, usuario[4]):
                flash('A nova senha não pode ser igual à atual ou a uma das 3 anteriores.', 'error')
                return redirect(url_for('editar_usuario'))
            hash_senha = bcrypt.generate_password_hash(senha).decode('utf-8')
            cursor.execute('''INSERT INTO HISTORICO_SENHA (ID_USUARIO, SENHA_HASH)
                              VALUES (?, ?)''', (session['id_usuario'], usuario[4]))
            cursor.execute('''UPDATE USUARIO SET NOME=?, EMAIL=?, SENHA=?, RECEITA_MENSAL=?, DESPESA_MENSAL=?
                              WHERE ID_USUARIO=?''', (nome, email, hash_senha, receita, despesa, session['id_usuario']))
        else:
            cursor.execute('''UPDATE USUARIO SET NOME=?, EMAIL=?, RECEITA_MENSAL=?, DESPESA_MENSAL=?
                              WHERE ID_USUARIO=?''', (nome, email, receita, despesa, session['id_usuario']))
        if senha:
            cursor.execute('''DELETE FROM HISTORICO_SENHA WHERE ID_USUARIO = ?
                              AND ID_HISTORICO NOT IN (
                                SELECT FIRST 3 ID_HISTORICO FROM HISTORICO_SENHA
                                WHERE ID_USUARIO = ? ORDER BY ID_HISTORICO DESC
                              )''', (session['id_usuario'], session['id_usuario']))
        con.commit()
        session['nome_usuario'] = nome
        flash('Dados atualizados.', 'success')
        return redirect(url_for('inicio'))
    except ValueError as e:
        flash(str(e), 'error')
        return redirect(url_for('editar_usuario'))
    except Exception:
        con.rollback()
        app.logger.exception('Falha na edição')
        flash('Não foi possível atualizar os dados.', 'error')
        return redirect(url_for('inicio'))
    finally:
        cursor.close()
        con.close()


@app.route('/logout', methods=['POST'])
@autenticado
def logout():
    session.clear()
    flash('Você saiu da sua conta.', 'success')
    return redirect(url_for('login'))


if __name__ == '__main__':
    preparar_seguranca()
    app.run(debug=os.environ.get('ARO_DEBUG') == '1')
