# Autenticação e cadastro do Banco ARO (Flask + Firebird).
# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
import os
# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
from functools import wraps
# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
from pathlib import Path
# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
from decimal import Decimal, InvalidOperation

# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
import fdb
# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
from flask import Flask, render_template, request, flash, redirect, url_for, session
# Puxa uma ferramenta pronta do Python para a gente conseguir usar aqui.
from flask_bcrypt import Bcrypt

# Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
BASE = Path(__file__).resolve().parent
# Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
app = Flask(__name__, template_folder=str(BASE / 'Templates'), static_folder=str(BASE / 'Static'), static_url_path='/static')
# Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
app.config['SECRET_KEY'] = os.environ.get('ARO_SECRET_KEY', 'CHAVE-LOCAL-TROQUE-ANTES-DE-PUBLICAR')
# Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
bcrypt = Bcrypt(app)
# Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
DB_PATH = Path(os.environ.get('ARO_DB_PATH', str(BASE.parent / 'BANCO.FDB')))


# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def conectar():
    # Devolve um resultado e termina a execução dessa função nesse ponto.
    return fdb.connect(host=os.environ.get('ARO_DB_HOST', 'localhost'),
                       # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
                       database=str(DB_PATH), user=os.environ.get('ARO_DB_USER', 'sysdba'),
                       # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
                       password=os.environ.get('ARO_DB_PASSWORD', 'masterkey'), charset='UTF8')



# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def preparar_seguranca():
    # Migração idempotente: executar com permissão DDL.
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    con = conectar()
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    cur = con.cursor()
    # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
    try:
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cur.execute("SELECT TRIM(RDB$FIELD_NAME) FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'USUARIO'")
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        campos = {r[0].upper() for r in cur.fetchall()}
        # Repete esse bloco para cada item que aparecer nessa lista ou resultado.
        for nome, tipo in [('ATIVO', 'SMALLINT DEFAULT 1 NOT NULL'),
                           # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
                           ('TENTATIVAS_LOGIN', 'SMALLINT DEFAULT 0 NOT NULL'),
                           # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
                           ('BLOQUEADO', 'SMALLINT DEFAULT 0 NOT NULL')]:
            # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
            if nome not in campos:
                # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
                cur.execute(f'ALTER TABLE USUARIO ADD {nome} {tipo}')
                # Confirma e salva de verdade as alterações feitas no banco.
                con.commit()
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cur.execute("SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'HISTORICO_SENHA'")
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if cur.fetchone()[0] == 0:
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cur.execute('''CREATE TABLE HISTORICO_SENHA (
                ID_HISTORICO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_USUARIO INTEGER NOT NULL,
                SENHA_HASH VARCHAR(255) NOT NULL,
                CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT FK_HIST_SENHA_USUARIO FOREIGN KEY (ID_USUARIO)
                    REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
            )''')
            # Confirma e salva de verdade as alterações feitas no banco.
            con.commit()
        # As senhas atuais são verificadas diretamente na tabela USUARIO.
        # O histórico só armazena senhas anteriores a partir da primeira troca.
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except Exception:
        # Desfaz as alterações dessa operação quando aconteceu um erro.
        con.rollback()
        # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
        raise
    # Esse bloco roda no final, mesmo se deu erro, para fechar recursos.
    finally:
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        cur.close()
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        con.close()


# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def senha_ja_utilizada(cursor, id_usuario, nova_senha, hash_atual):
    # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
    if bcrypt.check_password_hash(hash_atual, nova_senha):
        # Devolve um resultado e termina a execução dessa função nesse ponto.
        return True
    # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
    cursor.execute('''SELECT FIRST 3 SENHA_HASH FROM HISTORICO_SENHA
                      WHERE ID_USUARIO = ? ORDER BY ID_HISTORICO DESC''', (id_usuario,))
    # Usa bcrypt para criar ou conferir o hash seguro da senha, sem salvar a senha normal.
    return any(bcrypt.check_password_hash(item[0], nova_senha) for item in cursor.fetchall())


# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def senha_forte(senha):
    # Validação artesanal, usando funções nativas do Python.
    # Devolve um resultado e termina a execução dessa função nesse ponto.
    return (len(senha) >= 8 and any(c.isupper() for c in senha)
            # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
            and any(c.islower() for c in senha) and any(c.isdigit() for c in senha))


# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def valor_monetario(texto):
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    texto = (texto or '').strip().replace('R$', '').replace(' ', '')
    # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
    if ',' in texto:
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        texto = texto.replace('.', '').replace(',', '.')
    # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
    try:
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        valor = Decimal(texto)
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not valor.is_finite() or valor < 0:
            # Interrompe esse caminho porque foi encontrada uma situação inválida.
            raise ValueError()
        # Devolve um resultado e termina a execução dessa função nesse ponto.
        return valor
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except (InvalidOperation, ValueError):
        # Interrompe esse caminho porque foi encontrada uma situação inválida.
        raise ValueError('Informe valores válidos para renda e despesas.')


# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def autenticado(view):
    # Esse decorador acrescenta uma regra à função logo embaixo, como exigir login.
    @wraps(view)
    # Aqui começa uma função: o código dela só roda quando essa função é chamada.
    def protegido(*args, **kwargs):
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if 'id_usuario' not in session:
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Você precisa estar logado.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        con = conectar()
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        cur = con.cursor()
        # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
        try:
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cur.execute('SELECT ATIVO, BLOQUEADO FROM USUARIO WHERE ID_USUARIO = ?', (session['id_usuario'],))
            # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
            situacao = cur.fetchone()
        # Esse bloco roda no final, mesmo se deu erro, para fechar recursos.
        finally:
            # Fecha essa conexão ou cursor para não deixar recurso aberto.
            cur.close()
            # Fecha essa conexão ou cursor para não deixar recurso aberto.
            con.close()
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not situacao or not situacao[0] or situacao[1]:
            # Usa a sessão para lembrar quem entrou ou para sair da conta.
            session.clear()
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Conta inativa ou bloqueada. Entre em contato com o administrador.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Devolve um resultado e termina a execução dessa função nesse ponto.
        return view(*args, **kwargs)
    # Devolve um resultado e termina a execução dessa função nesse ponto.
    return protegido


# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/')
# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def landing():
    # Pede para o Flask montar e mostrar essa página HTML.
    return render_template('landing.html')


# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/cadastro', methods=['GET', 'POST'])
# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def cadastro():
    # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
    if request.method == 'GET':
        # Pede para o Flask montar e mostrar essa página HTML.
        return render_template('cadastro.html')
    # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
    nome = request.form.get('nome', '').strip()
    # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
    email = request.form.get('email', '').strip().lower()
    # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
    senha = request.form.get('senha', '')
    # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
    if not nome or not email or not senha:
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Preencha nome, e-mail e senha.', 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('cadastro'))
    # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
    if not senha_forte(senha):
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Use pelo menos 8 caracteres, com maiúscula, minúscula e número.', 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('cadastro'))
    # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
    try:
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        receita = valor_monetario(request.form.get('renda'))
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        despesa = valor_monetario(request.form.get('despesas'))
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except ValueError as e:
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash(str(e), 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('cadastro'))
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    con = conectar()
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    cursor = con.cursor()
    # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
    try:
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cursor.execute('SELECT 1 FROM USUARIO WHERE LOWER(EMAIL) = ?', (email,))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if cursor.fetchone():
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Este e-mail já foi cadastrado.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('cadastro'))
        # Usa bcrypt para criar ou conferir o hash seguro da senha, sem salvar a senha normal.
        hash_senha = bcrypt.generate_password_hash(senha).decode('utf-8')
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cursor.execute('''INSERT INTO USUARIO
            (NOME, EMAIL, SENHA, RECEITA_MENSAL, DESPESA_MENSAL, TIPO_USUARIO)
            VALUES (?, ?, ?, ?, ?, ?)''', (nome, email, hash_senha, receita, despesa, 1))
        # Confirma e salva de verdade as alterações feitas no banco.
        con.commit()
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Cadastro realizado! Entre na sua conta.', 'success')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('login'))
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except Exception:
        # Desfaz as alterações dessa operação quando aconteceu um erro.
        con.rollback()
        # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
        app.logger.exception('Falha no cadastro')
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Não foi possível concluir o cadastro.', 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('cadastro'))
    # Esse bloco roda no final, mesmo se deu erro, para fechar recursos.
    finally:
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        cursor.close()
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        con.close()


# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/login', methods=['GET', 'POST'])
# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def login():
    # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
    if request.method == 'GET':
        # Pede para o Flask montar e mostrar essa página HTML.
        return render_template('login.html')
    # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
    email = request.form.get('email', '').strip().lower()
    # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
    senha = request.form.get('senha', '')
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    con = conectar()
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    cursor = con.cursor()
    # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
    try:
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cursor.execute('''SELECT ID_USUARIO, NOME, SENHA, ATIVO, TENTATIVAS_LOGIN, BLOQUEADO
                          FROM USUARIO WHERE LOWER(EMAIL) = ?''', (email,))
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        usuario = cursor.fetchone()
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not usuario:
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('E-mail ou senha incorretos.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        id_usuario, nome, senha_hash, ativo, tentativas, bloqueado = usuario
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not ativo:
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Usuário inativo. Entre em contato com o administrador.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if bloqueado or tentativas >= 3:
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Usuário bloqueado após 3 tentativas. Entre em contato com o administrador.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not bcrypt.check_password_hash(senha_hash, senha):
            # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
            tentativas = (tentativas or 0) + 1
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cursor.execute('''UPDATE USUARIO SET TENTATIVAS_LOGIN = ?, BLOQUEADO = ?
                              WHERE ID_USUARIO = ?''', (tentativas, 1 if tentativas >= 3 else 0, id_usuario))
            # Confirma e salva de verdade as alterações feitas no banco.
            con.commit()
            # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
            if tentativas >= 3:
                # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
                flash('Usuário bloqueado após 3 tentativas incorretas.', 'error')
            # Se nenhuma das condições anteriores passou, faz esse caminho.
            else:
                # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
                flash(f'E-mail ou senha incorretos. Tentativa {tentativas} de 3.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cursor.execute('UPDATE USUARIO SET TENTATIVAS_LOGIN = 0 WHERE ID_USUARIO = ?', (id_usuario,))
        # Confirma e salva de verdade as alterações feitas no banco.
        con.commit()
        # Usa a sessão para lembrar quem entrou ou para sair da conta.
        session.clear()
        # Usa a sessão para lembrar quem entrou ou para sair da conta.
        session['id_usuario'] = id_usuario
        # Usa a sessão para lembrar quem entrou ou para sair da conta.
        session['nome_usuario'] = nome
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Login realizado com sucesso!', 'success')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('inicio'))
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except Exception:
        # Desfaz as alterações dessa operação quando aconteceu um erro.
        con.rollback()
        # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
        app.logger.exception('Falha no login')
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Não foi possível entrar no momento.', 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('login'))
    # Esse bloco roda no final, mesmo se deu erro, para fechar recursos.
    finally:
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        cursor.close()
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        con.close()


# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/inicio')
# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/novo')
# Esse decorador acrescenta uma regra à função logo embaixo, como exigir login.
@autenticado
# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def inicio():
    # Pede para o Flask montar e mostrar essa página HTML.
    return render_template('inicio.html', usuario=session['nome_usuario'])


# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/editar_usuario', methods=['GET', 'POST'])
# Esse decorador acrescenta uma regra à função logo embaixo, como exigir login.
@autenticado
# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def editar_usuario():
    # Edita o usuário autenticado sem modificar a chave primária.
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    con = conectar()
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    cursor = con.cursor()
    # Tenta executar esse pedaço do código e fica pronto para tratar algum erro.
    try:
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cursor.execute('''SELECT NOME, EMAIL, RECEITA_MENSAL, DESPESA_MENSAL, SENHA
                          FROM USUARIO WHERE ID_USUARIO = ?''', (session['id_usuario'],))
        # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
        usuario = cursor.fetchone()
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not usuario:
            # Usa a sessão para lembrar quem entrou ou para sair da conta.
            session.clear()
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Usuário não encontrado.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('login'))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if request.method == 'GET':
            # Pede para o Flask montar e mostrar essa página HTML.
            return render_template('editar_usuario.html', usuario=usuario)
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        nome = request.form.get('nome', '').strip()
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        email = request.form.get('email', '').strip().lower()
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        senha = request.form.get('senha', '')
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if not nome or not email:
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Nome e e-mail são obrigatórios.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('editar_usuario'))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if senha and not senha_forte(senha):
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('A nova senha deve ter 8 caracteres, maiúscula, minúscula e número.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('editar_usuario'))
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        receita = valor_monetario(request.form.get('renda'))
        # Pega o valor enviado pelo formulário HTML; o nome tem que bater com o name do campo.
        despesa = valor_monetario(request.form.get('despesas'))
        # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
        cursor.execute('SELECT 1 FROM USUARIO WHERE LOWER(EMAIL) = ? AND ID_USUARIO <> ?',
                       # Usa a sessão para lembrar quem entrou ou para sair da conta.
                       (email, session['id_usuario']))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if cursor.fetchone():
            # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
            flash('Este e-mail já está em uso.', 'error')
            # Manda o navegador abrir outro endereço depois dessa ação.
            return redirect(url_for('editar_usuario'))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if senha:
            # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
            if senha_ja_utilizada(cursor, session['id_usuario'], senha, usuario[4]):
                # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
                flash('A nova senha não pode ser igual à atual ou a uma das 3 anteriores.', 'error')
                # Manda o navegador abrir outro endereço depois dessa ação.
                return redirect(url_for('editar_usuario'))
            # Usa bcrypt para criar ou conferir o hash seguro da senha, sem salvar a senha normal.
            hash_senha = bcrypt.generate_password_hash(senha).decode('utf-8')
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cursor.execute('''INSERT INTO HISTORICO_SENHA (ID_USUARIO, SENHA_HASH)
                              VALUES (?, ?)''', (session['id_usuario'], usuario[4]))
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cursor.execute('''UPDATE USUARIO SET NOME=?, EMAIL=?, SENHA=?, RECEITA_MENSAL=?, DESPESA_MENSAL=?
                              WHERE ID_USUARIO=?''', (nome, email, hash_senha, receita, despesa, session['id_usuario']))
        # Se nenhuma das condições anteriores passou, faz esse caminho.
        else:
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cursor.execute('''UPDATE USUARIO SET NOME=?, EMAIL=?, RECEITA_MENSAL=?, DESPESA_MENSAL=?
                              WHERE ID_USUARIO=?''', (nome, email, receita, despesa, session['id_usuario']))
        # Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
        if senha:
            # Envia um comando SQL para o banco Firebird; os ? recebem os valores sem montar SQL na mão.
            cursor.execute('''DELETE FROM HISTORICO_SENHA WHERE ID_USUARIO = ?
                              AND ID_HISTORICO NOT IN (
                                SELECT FIRST 3 ID_HISTORICO FROM HISTORICO_SENHA
                                WHERE ID_USUARIO = ? ORDER BY ID_HISTORICO DESC
                              )''', (session['id_usuario'], session['id_usuario']))
        # Confirma e salva de verdade as alterações feitas no banco.
        con.commit()
        # Usa a sessão para lembrar quem entrou ou para sair da conta.
        session['nome_usuario'] = nome
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Dados atualizados.', 'success')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('inicio'))
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except ValueError as e:
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash(str(e), 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('editar_usuario'))
    # Se acontecer esse tipo de erro, cai nesse bloco em vez de parar o site.
    except Exception:
        # Desfaz as alterações dessa operação quando aconteceu um erro.
        con.rollback()
        # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
        app.logger.exception('Falha na edição')
        # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
        flash('Não foi possível atualizar os dados.', 'error')
        # Manda o navegador abrir outro endereço depois dessa ação.
        return redirect(url_for('inicio'))
    # Esse bloco roda no final, mesmo se deu erro, para fechar recursos.
    finally:
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        cursor.close()
        # Fecha essa conexão ou cursor para não deixar recurso aberto.
        con.close()


# Essa é uma rota: liga um endereço do site à função logo embaixo. GET abre a tela e POST recebe os dados.
@app.route('/logout', methods=['POST'])
# Esse decorador acrescenta uma regra à função logo embaixo, como exigir login.
@autenticado
# Aqui começa uma função: o código dela só roda quando essa função é chamada.
def logout():
    # Usa a sessão para lembrar quem entrou ou para sair da conta.
    session.clear()
    # Guarda uma mensagem para aparecer na página, como aviso de erro ou sucesso.
    flash('Você saiu da sua conta.', 'success')
    # Manda o navegador abrir outro endereço depois dessa ação.
    return redirect(url_for('login'))


# Aqui o código confere uma condição; se for verdadeira, entra nesse bloco.
if __name__ == '__main__':
    # Essa instrução faz parte da lógica que está sendo executada nesse bloco.
    preparar_seguranca()
    # Aqui um valor está sendo guardado numa variável ou uma informação está sendo configurada.
    app.run(debug=os.environ.get('ARO_DEBUG') == '1')
